import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar/Navbar";

const outfitFont = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className={`${outfitFont.className} h-full antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}